### ISSUE TITLE
Unable to npm install vue-roller via Vue CLI 4.5

### ISSUE THREAD

**Issue by HamidKhaldi** [Andy-0414/vue-roller#27]
Every time I try to install the dependency, I get this error:

Run `npm audit` for details.
PS C:\Users\FG633UW\OneDrive - EY\Desktop\EY-Sharepoint\Creative-London-Vue\csg-showcase-sp> npm install vue-roller --save
(node:15588) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: vue@3.2.20
npm ERR! node_modules/vue
npm ERR!   peerOptional vue@"^2 || ^3.0.0-0" from @vue/babel-preset-app@4.5.13
npm ERR!   node_modules/@vue/babel-preset-app
npm ERR!     @vue/babel-preset-app@"^4.5.13" from @vue/cli-plugin-babel@4.5.13
npm ERR!     node_modules/@vue/cli-plugin-babel
npm ERR!       dev @vue/cli-plugin-babel@"~4.5.0" from the root project
npm ERR!   peer vue@"3.2.20" from @vue/server-renderer@3.2.20
npm ERR!   node_modules/@vue/server-renderer
npm ERR!     @vue/server-renderer@"3.2.20" from vue@3.2.20
npm ERR!   2 more (vue-router, the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.0.0" from vue-class-component@7.2.6
npm ERR! node_modules/vue-property-decorator/node_modules/vue-class-component
npm ERR!   vue-class-component@"^7.1.0" from vue-property-decorator@8.5.1
npm ERR!   node_modules/vue-property-decorator
npm ERR!     vue-property-decorator@"^8.4.2" from vue-roller@1.12.5
npm ERR!     node_modules/vue-roller
npm ERR!       vue-roller@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

Then when I install it using --legacy-peer-deps, and I follow the steps, I get this error in the console:
vue-roller.common.js?92da:4372 
        
       Uncaught TypeError: Super expression must either be null or a function
    at _inherits (vue-roller.common.js?92da:4372)
    at eval (vue-roller.common.js?92da:5343)
    at Module.fb15 (vue-roller.common.js?92da:5443)
    at __webpack_require__ (vue-roller.common.js?92da:21)
    at eval (vue-roller.common.js?92da:85)
    at eval (vue-roller.common.js?92da:88)
    at Object../node_modules/vue-roller/dist/vue-roller.common.js (chunk-vendors.js:1652)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (Home.js?3f5a:1)

Can someone please help? I am working to a deadline and would like to use this dependency as it really fits the bill.

**Comment by Andy-0414** [comment]
Sorry. This is a problem that needs to be resolved by upgrading to Vue 3, and we will try to apply it as soon as possible..

**Comment by Andy-0414** [comment]
@HamidKhaldi Vue3 support has been completed. You can use the beta version right away! 👏
