### ISSUE TITLE
Bug Won't show all of numbers just the start of the number (v 1.8.1)

### ISSUE THREAD

**Issue by TG4LAaron** [Andy-0414/vue-roller#3]
As you can see from the demo it won't show all of the number just the first bit of the number

https://codesandbox.io/s/modest-mcclintock-i4gkk?file=/src/pages/Index.vue Broken Demo on version: 1.8.1

https://codesandbox.io/s/magical-wright-m16mx?file=/src/pages/Index.vue Working Demo on version: 1.6.6
Works fine in verison 1.6.6 as you can see by the link above

**Comment by TG4LAaron** [comment]
@Andy-0414 Any news?

**Comment by Andy-0414** [comment]
Sorry. We will contact you after confirmation.

**Comment by Andy-0414** [comment]
![image](https://user-images.githubusercontent.com/37619661/86463354-4d56bd00-bd68-11ea-9316-f1479b4a0933.png)

https://codesandbox.io/s/compassionate-panini-myvzn?file=/src/pages/Index.vue

I think it's a bug that occurred after making the .block class customizable. I will rename the class in the next version.

**Comment by Andy-0414** [comment]
Updating to version 1.9.0 will fix the problem.
