### ISSUE TITLE
Multi-line text

### ISSUE THREAD

**Issue by antoinezanardi** [Andy-0414/vue-roller#4]
First of all, thanks for your work on this plugin. I'm already using it on several projects to make awesome text transitions.

I wanted to know if multi-line text is planned ? I faced several issues while working on small screens: the text is not rendered entirely. You can reproduce this issue on the demo page by typing a long text.

Thanks and keep up the good work 👍 !

**Comment by Andy-0414** [comment]
Multi-line text and text wrap are being prepared. Thank you for using 👍 !

**Comment by antoinezanardi** [comment]
Thanks for the reply ! Any ideas when this will be available ?

**Comment by Andy-0414** [comment]
After testing for about a week, if there is no problem with the function, we will update it!

**Comment by Andy-0414** [comment]
The multi line function has been updated. Please check.

**Comment by antoinezanardi** [comment]
After some tests, it looks like words are truncated from one line to another.

For example:
|-------------------|
|I'm a very cool  feat|
|ure.                          |
|-------------------|

Is it possible to implement an option for word-break ? Would be perfect.

Apart from that, I didn't face any bug or undesirable behavior.

Thanks for your work, this is a big step 👍🏻 !

**Comment by Andy-0414** [comment]
Added **wordWrap** function. Please report any bugs.
The function of automatically **wordWrap** to fit the width has not been developed yet.

**Comment by antoinezanardi** [comment]
Thanks a lot for your work. To be honest, wordWrap with fixed width is not my need but can be for other people.

The multi-line feature is done, we can close this issue.

But before that, I have two more requests:

- When will the wordWrap according to width will be available ?

- It appears that the prop **defaultChar** is not working anymore. When you set same value for **text** and **defaultChar**, the animation still rolls. Is it intended ? 

What do you prefer ? Keep going on this thread or you want me to create two issues for each subject and close this issue ?

Thanks a lot for your work 🤟🏼

**Comment by Andy-0414** [comment]
When will the wordWrap according to width be available ?

**Comment by Andy-0414** [comment]
- When will the wordWrap according to width be available ?

If you do not have any special bugs while creating this feature, it will be released within this month.

- It appears that the prop **defaultChar** is not working anymore. When you set same value for **text** and **defaultChar**, the animation still rolls. Is it intended ?

Yes, this is a minor bug that occurred while implementing wordWrap, and it was fixed.

Also, if you have a new bug, please open a new issue.
Thanks 👍
