### ISSUE TITLE
Maybe a bug copying the text

### ISSUE THREAD

**Issue by TG4LAaron** [Andy-0414/vue-roller#5]
When you try and copy the numbers it won't copy the right numbers/text

https://pastebin.com/xYVTa02G

https://andy-0414.github.io/vue-roller/ happens there too try and copy the example numbers 1234

**Comment by Andy-0414** [comment]
I am aware of this bug and will try to fix it as soon as possible.

**Comment by Andy-0414** [comment]
It's corrected. Thanks for the good feedback. :)
