### ISSUE TITLE
defaultChar property still triggers animation on start

### ISSUE THREAD

**Issue by antoinezanardi** [Andy-0414/vue-roller#7]
Looks like there is still a bug when defaultChar property is set.

When I set the property, the animation still rolls when the page loads.

I'm on latest version: **v1.12.1**, am I missing something ?

Thanks for your work 👍🏻 !

**Comment by Andy-0414** [comment]
I will check and fix it now! please wait a moment!

**Comment by antoinezanardi** [comment]
Here is the code I used:

```javascript
<VRoller :default-char="oneTargetPlayRequirementsText" :text="oneTargetPlayRequirementsText"/>
```

`oneTargetPlayRequirementsText` is a computed property defined like below:

```javascript
oneTargetPlayRequirementsText() {
   return this.$t("GamePlayFieldFooter.playersTargeted", { targetsCount: this.play.targets.length, min: 1 });
},
```

This property is available on page load so the animation is not supposed to trigger, right ?

**Comment by antoinezanardi** [comment]
Ok, I just tested it again with the new version *v1.12.2*.

The animation doesn't roll anymore with the characters in the `char-list` property.

For example, I have this text with `vue-roller`: "5 / 5 alive"

The animation will roll for the characters `/`, `alive` because they are not in the `char-list`. Is it normal ?

Thanks for your fast replies, appreciated 👍🏻

**Comment by Andy-0414** [comment]
It is normal that`/`, `alive` is not animated.

**Comment by antoinezanardi** [comment]
Indeed, they are animated. Characters in `char-list` are not animated but the others like `/` or `alive` are animated on page load.

**Comment by Andy-0414** [comment]
I have confirmed this issue and am working on it.

**Comment by Andy-0414** [comment]
Please try again with the new version.

**Comment by antoinezanardi** [comment]
The issue is fixed ! Thanks for your work 👌🏼
