### ISSUE TITLE
$attrs is readonly

### ISSUE THREAD

**Issue by daniel-cabane** [Andy-0414/vue-roller#9]
Hello, I am working on a project with Vue (using Vuetify). I just added vue-roller which works fine, except that every time that the text of the roller changes I get 2 vue warnings :

- [Vue warn]: $attrs is readonly.
- [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "text"

Would you have any idea how I can fix this ?
Thanks !

**Comment by Andy-0414** [comment]
```javascript
@Prop({ default: "0000", type: String as PropType<string>, required: true })
readonly text!: string;
```
This is the code that works now

**Comment by daniel-cabane** [comment]
Thanks for the quick response !
I am not sure how I can send you the code as it is within a rather large project. Here's what I have :
If I write
`<Roller text="1234"></Roller>`
I get the following warnings : 
- [Vue warn]: $attrs is readonly.
- [Vue warn]: $listeners is readonly.

The code
`<Roller :text="myComputedProp"></Roller>`
where myComputedProp is a computed property which returns a string, I get the same warnings and then whenever the computed property changes, I get the warnings
- [Vue warn]: $attrs is readonly.
- [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "text"

To give you some background, this is in a laravel 5.7 + vue 2.5 project. Below is my package.json
`
"devDependencies": {
        "axios": "^0.18.1",
        "cross-env": "^5.1",
        "laravel-mix": "^4.0.15",
        "lodash": "^4.17.19",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.26.3",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.6"
    },
    "dependencies": {
        "@codekraft-studio/vue-animated": "^0.1.3",
        "chart.js": "^2.9.3",
        "katex": "^0.10.0",
        "laravel-echo": "^1.8.1",
        "material-design-icons-iconfont": "^4.0.4",
        "mathjs": "^5.8.0",
        "moment": "^2.24.0",
        "moment-timezone": "^0.5.25",
        "pusher-js": "^7.0.0",
        "sortablejs": "^1.9.0",
        "vue-avatar-editor-improved": "^1.0.4",
        "vue-card-stack": "^1.2.1",
        "vue-cropperjs": "^3.0.0",
        "vue-roller": "^1.12.3",
        "vue-router": "^3.0.3",
        "vuedraggable": "^2.21.0",
        "vuetify": "^1.5.1"
    }
`

**Comment by Andy-0414** [comment]
When I try it myself, the error does not appear.
First of all, I will keep this issue open. Please send the error code by making an example using codepan or other service.
Then we will fix it as soon as possible.

**Comment by daniel-cabane** [comment]
Hello again, I tried to test some things out and I am still stuck...
I added a roller in another part of my project and it works just fine (I love the animation BTW, great job !).
I guess the first error is probably just me messing up the wiring... I'll keep looking for a solution to my original problem, but in the meantime, if you want to close this issue, I totally understand.
FYI I am not a professional developer and I don't have time to work on this regularly, so it might take me a while before I figure things out.

**Comment by daniel-cabane** [comment]
I am sorry I haven't been able to find the cause of my problem. I also haven't been able to reproduce it anywhere I could share the code with you. Just FYI I am not a professional developer so I might have wired something wrong from the start. Also, I can't spend too much time on this.
I guess without any hope of progress, you can probably close or delete this issue.
Great work BTW, I love the animation of your roller !

**Comment by Andy-0414** [comment]
Sorry for not helping.
If you find the cause of the error or reproduce the situation, we will fix it!

**Comment by henriquevc** [comment]
I had the same problem here, but i find the cause. 
I'm using the vue-roller together with vue-svg-gauge and when both are being used, it gives the error of "Vue warn]: $attrs is readonly" and "[Vue warn]: $listeners is readonly.". 
When I comment the line where I use vue-svg-gauge, the error disappear.
So, try to remove some components that are being used together with vue-roller and observe if the error persists.

**Comment by Andy-0414** [comment]
Let's check it out quickly!

**Comment by mikadev** [comment]
Hello any solution  ? i had the same problem

**Comment by Andy-0414** [comment]
Vue3 support has been completed. You can use the beta version right away! 👏
